version: '2'

services:
#######################################################################
  S_nginx:
    image: nginx
    container_name: C_nginx
    hostname: nginx
    links:
      - "S_jira:srv_jirs"
    ports:
      - "80:80"
      - "443:443"
    networks:
       pgsql:
          ipv4_address: 172.22.0.3
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro" 
    restart: unless-stopped

#docker run --name my-custom-nginx-container -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx

#######################################################################
  S_jira:
    image: cptactionhank/atlassian-jira
    container_name: C_jira
#    hostname: jira
    environment:
       CATALINA_OPTS: -Xms2048m -Xmx2048m -Datlassian.plugins.enable.wait=300
    ports:
      - "8080:8080"
      - "8081:8081" 
    networks:
       pgsql:
          ipv4_address: 172.22.0.4
    volumes:
      - ./jira/server.xml:/opt/atlassian/jira/conf/server.xml
    restart: unless-stopped

#  --volume "hostpath:/var/atlassian/jira" \
#  --env "CATALINA_OPTS= -Xms2048m -Xmx2048m -Datlassian.plugins.enable.wait=10" \

#######################################################################
  S_postgres:
    image: postgres
    container_name: C_postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - ./pgsql/env_db_postgres4jira
    restart: unless-stopped
    networks:
       pgsql:
          ipv4_address: 172.22.0.5     
    volumes:
#      - /root/postgres-pass:/run/secrets/postgres-pass
#      - /opt/intersystems/postgres/data:/var/lib/postgresql/data
      - ./pgsql/01_modify_pghba.sh:/docker-entrypoint-initdb.d/01_modify_pghba.sh
      - ./pgsql/02_create-jira-pgdb.sql:/docker-entrypoint-initdb.d/02_create-jira-pgdb.sql
#      - ./pgsql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - V_db-pgsql:/var/lib/postgresql/data

#######################################################################
volumes:
#    V_db-mysql:
    V_db-pgsql:
#######################################################################
networks:
   pgsql:
     driver: bridge
     ipam:
      config:
        - subnet:  172.22.0.0/28


