version: '2'

services:
#######################################################################
  S_nginx:
    image: nginx
    container_name: C_nginx
    hostname: nginx
    links:
      - "S_jira:srv_jirs"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro" 
    restart: unless-stopped

#docker run --name my-custom-nginx-container -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx

#######################################################################
  S_jira:
    image: cptactionhank/atlassian-jira
    container_name: C_jira
#    hostname: jira
    ports:
      - "8080:8080"
      - "8081:8081" 
    volumes:
      - ./jira/server.xml:/opt/atlassian/jira/conf/server.xml
    restart: unless-stopped

#docker run --detach --publish 8080:8080 cptactionhank/atlassian-jira-software:latest
#######################################################################
  S_postgres:
    image: postgres
    container_name: C_postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
#      - /root/postgres-pass:/run/secrets/postgres-pass
#      - /opt/intersystems/postgres/data:/var/lib/postgresql/data
      - ./pgsql/01_create-jira-pgdb.sql:/docker-entrypoint-initdb.d/01_create-jira-pgdb.sql
      - ./pgsql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - V_db-pgsql:/var/lib/postgresql/data
    env_file:
      - ./pgsql/env_db_postgres4jira
    restart: unless-stopped

#######################################################################
volumes:
#    V_db-mysql:
    V_db-pgsql:
#######################################################################
